name: hoa_lo_ar_discovery
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  english_words: ^4.0.0
  provider: ^6.0.0
  animate_do: ^3.1.2
  dots_indicator: ^3.0.0
  carousel_slider: ^4.2.1
  floating_bottom_navigation_bar: ^1.5.2
  easy_settings: ^1.0.0
  path_provider: ^2.0.5
  video_player: ^2.2.11 # Số phiên bản cụ thể có thể thay đổi
  chewie: ^1.7.5
  intl: ^0.19.0
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.0
  animated_text_kit: ^4.2.2
  flutter_dotenv: ^5.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/image/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"


flutter:
  uses-material-design: true
  assets:
    - assets/image/intro/1.jpg
    - assets/image/intro/2.jpg
    - assets/image/intro/3.jpg
    - assets/image/home/bg_detail.jpg
    - assets/image/home/bg_home.jpg
    - assets/image/home/bg_app_bar.png
    - assets/image/home/bg_app_bar_detail.png
    - assets/image/home/bg_app_bar_ai.png
    - assets/image/home/bg_brown.png
    - assets/image/home/bg_setting.png
    - assets/image/map/map.jpg
    - assets/image/map/map_vertical.jpg
    - assets/image/map/legend.jpg
    - assets/image/item/cachot_01.jpg
    - assets/image/item/cachot_02.jpg
    - assets/image/item/cachot_03.jpg
    - assets/image/item/trainam_01.jpg
    - assets/image/item/trainam_02.jpg
    - assets/image/item/trainam_03.jpg
    - assets/database/db_items.json
    - assets/image/item/canh_cua_nha_tu.jpg
    - assets/image/item/trainu_02.jpg
    - assets/image/item/trainu_01.jpg
    - assets/image/item/trainu_03.jpg
    - assets/image/item/cay_bang_tinh_nghia.jpg
    - assets/image/item/cum_chan.jpg
    - assets/image/item/dia_thia.jpg
    - assets/image/item/bat.jpg
    - assets/image/item/quan_ao.jpg
    - assets/image/item/che_do_an_uong_1.jpg
    - assets/image/item/che_do_an_uong_2.jpg
    - assets/image/item/phi_cong_my_1.jpg
    - assets/image/item/phi_cong_my_2.jpg
    - assets/image/item/maychem_01.jpg
    - assets/image/item/maychem_02.jpg
    - assets/image/item/maychem_03.jpg
    - assets/image/item/maychem_04.jpg
    - assets/database/db_items.json
    - assets/video/hoalo_intro.mp4
    - assets/video/hoalo_intro2.mp4
    - assets/languages/language.json
