name: hoa_lo_ar_discovery
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1  # Ví dụ với package http và phiên bản 0.13.3

  english_words: ^4.0.0
  provider: ^6.0.0
  animate_do: ^3.1.2
  dots_indicator: ^3.0.0
  carousel_slider: ^4.2.1
  floating_bottom_navigation_bar: ^1.5.2
  easy_settings: ^1.0.0
  path_provider: ^2.0.5 
  video_player: ^2.2.11 # Số phiên bản cụ thể có thể thay đổi
  chewie: ^1.7.5
  intl: ^0.19.0
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.0
  animated_text_kit: ^4.2.2
  flutter_dotenv: ^5.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/intro/intro1.jpg
    - assets/image/intro/intro2.jpg
    - assets/image/intro/intro3.jpg
    - assets/image/home/background.png
    - assets/image/map/map.jpg
    - assets/image/map/map_vertical.jpg
    - assets/image/map/legend.jpg
    - assets/image/item/cachot_01.jpg
    - assets/image/item/cachot_02.jpg
    - assets/image/item/cachot_03.jpg
    - assets/image/item/trainam_01.jpg
    - assets/image/item/trainam_02.jpg
    - assets/image/item/trainam_03.jpg
    - assets/database/db_items.json
    - assets/video/hoalo_intro.mp4
    - assets/languages/language.json
  